# Generated by Django 4.2.1 on 2023-05-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='products',
        ),
        migrations.AddField(
            model_name='link',
            name='orders',
            field=models.ManyToManyField(to='core.order'),
        ),
    ]
