# Generated by Django 4.2.1 on 2023-05-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_link_products_link_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='orders',
        ),
        migrations.AddField(
            model_name='link',
            name='products',
            field=models.ManyToManyField(to='core.product'),
        ),
    ]
